### ISSUE TITLE
Jiggling armatures that disable while off-screen don't stop the jiggle simulation

### ISSUE THREAD

**Issue by naelstrof** [naelstrof/UnityJigglePhysics#16]
This causes the jiggle physics to "catch-up" once its visible again.

**Comment by anhtien0369** [comment]
there are two method PrepareTeleport and FinishTeleport in class JiggleRigBuilder, u can use it before disable the jiggle object and after enable the jiggle object. Its gonna solve your problem

**Comment by naelstrof** [comment]
This is no longer a problem with our new LOD system (version 10)
