### ISSUE TITLE
ShaderGraph version not work.

### ISSUE THREAD

**Issue by Kovacs-3d** [naelstrof/UnityJigglePhysics#18]
Hello. Can you check what the problem might be? If I switch URPJigglePhysicsSoftbody.shadergraph, the vertex disappears.
![prblem1](https://user-images.githubusercontent.com/62808083/213814689-76bc5f5b-6ab7-4bd3-89f4-c377d0037219.jpg)
I tried the way it is in the ASE shader but it doesn't work I don't understand.
![prblem2](https://user-images.githubusercontent.com/62808083/213815331-e58bc52a-a092-45c5-9819-280bcecf41b5.jpg)

**Comment by Kovacs-3d** [comment]
Yeah, okay. I was looking at your shader and saw that it's local movement. you still need to add the original vertex positions at the end.
![work](https://user-images.githubusercontent.com/62808083/213820427-e13e32a6-af90-41b2-99de-76b1fdee0897.jpg)

**Comment by naelstrof** [comment]
Yeah sorry, I made the original code node with respect to Amplify Shader's defaults which uses local space offsets.

You found the intended solution just fine!
