### ISSUE TITLE
SendMessage cannot be called during

### ISSUE THREAD

**Issue by SnoupS** [naelstrof/UnityJigglePhysics#21]
SendMessage cannot be called during Awake, CheckConsistency, or OnValidate (JiggleBoneSphereCollider: OnDidAddCom

HDRP Unity 2023.2.0.b2
![image](https://github.com/naelstrof/UnityJigglePhysics/assets/39022810/077836c3-9bb4-4b58-8260-552836d50901)

**Comment by naelstrof** [comment]
Which version of JigglePhysics is this? Does it happen with v6.1.1?

**Comment by naelstrof** [comment]
Should be fixed with tag v6.1.2, thank you for the report!
