### ISSUE TITLE
[Question] Is there a way to constrain or limit the amount of rotation for a joint?

### ISSUE THREAD

**Issue by DawarAlvi** [naelstrof/UnityJigglePhysics#23]
I would like to know if we can limit the amount a joint can rotate per axis, similar to a Configurable Joint Angular Limit options.
![image](https://github.com/naelstrof/UnityJigglePhysics/assets/46403138/101ef156-0549-484f-8354-a577d7c24a31)
An option on the JiggleRigbuilder that affects only the root or on the Jiggle Settings that affect all the joints in the chain (except for the ignored transforms) would work really well.
![image](https://github.com/naelstrof/UnityJigglePhysics/assets/46403138/23a7baf3-5180-4f9e-8c1b-e67904d8d74d)
![image](https://github.com/naelstrof/UnityJigglePhysics/assets/46403138/eb9102d7-bae9-44e9-a19e-1b13598c1f56)

**Comment by naelstrof** [comment]
There's no such option unfortunately, however you can get very similar results by doing things like-- if you want a 90 degree limit you could set Blend to 0.5.
