### ISSUE TITLE
How to modify the transform bones at runtime.

### ISSUE THREAD

**Issue by The-Patriach** [naelstrof/UnityJigglePhysics#24]
For procedural characters compatibility. Can you provide an example of how can I access a JiggleRig inside a JiggleRigBuilder and change the root transform, add collisions, etc? Thank you.

**Comment by naelstrof** [comment]
You should be able to simply edit the bones on Update from another script, and JiggleRigBuilder should automatically detect the changes, provided that the "Animated" bool is checked on the rig. Sorry for the late response!
