### ISSUE TITLE
NameSpace Error

### ISSUE THREAD

**Issue by NasbyCroco** [naelstrof/UnityJigglePhysics#25]
I'm getting a namespace error in Unity on my project.

![Capture](https://github.com/naelstrof/UnityJigglePhysics/assets/154874396/0bcbb42e-37f0-4fb4-83e7-8bca6109fde7)!

**Comment by naelstrof** [comment]
Oh shoot! My bad I somehow pushed a bad branch. I usually install jiggle physics via tag so I didn't notice. Thank you for the report.

I should be fixed on 63040cd8193758910b263249adb8c366cea97734

`https://github.com/naelstrof/UnityJigglePhysics.git#v7.0.1`
