### ISSUE TITLE
Is it possible to do something similar with Lethal Expansion? 

### ISSUE THREAD

**Issue by subzerohurley** [naelstrof/UnityJigglePhysics#26]
I've wanted to add jiggle physics to scraps for a little while but Lethal Expansion doesnt have it packed into it

**Comment by naelstrof** [comment]
yeah actually, though I didn't really have the foresight for it. I don't think there's an issue with including the jigglephysics in as many dlls as you want. It is also possible to simply use the jigglephysics from the ModelReplacementAPI, but then you'd need it installed for it to work.

It would also be possible for me to simply create a jigglephysics addon that's a dependency, but I assumed most users would be annoyed by having yet another dll to drag into their project.

**Comment by subzerohurley** [comment]
To be fair, most users use a Mod manager like Thunderstore or R2, Right? Wouldn't that mean if I labeled a scrap on thunderstore as needed the dependency it would automatically download it? 
If so i would Absolutely love to have that! Especially after the unfortunate news of Holographic moving on from Lethal Expansion and looking for someone to take it from it.
