### ISSUE TITLE
Namespace error on Package Manager Import

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [naelstrof/UnityJigglePhysics#27]
like in [Issue 25](https://github.com/naelstrof/UnityJigglePhysics/issues/25)
I am getting namespace errors on import through UPM.
![267HBkVKWc](https://github.com/naelstrof/UnityJigglePhysics/assets/54823358/9750a739-ac48-4964-b7e3-8ab683a05ab6)

Running Unity 22.3.9f1 with JigglePhysics 7.0.2

**Comment by naelstrof** [comment]
Hmmm. I'm not sure how that's possible. 84b7dc is the correct hash-- I copied your setup and it works on my system (though I used 2022.3.10f1).

What happens if you install `https://github.com/naelstrof/UnityJigglePhysics.git#v7.0.2` rather than the upm branch?

**Comment by naelstrof** [comment]
I realize you're importing through UPM, I haven't actually tested that installation in a long time. I usually just put the git URL I need within the unity package manager. Let me know if that has a different result, I haven't changed how I publish upm content, but their package manager could have a bug!

**Comment by HokoraYinphineMPP** [comment]
> What happens if you install `https://github.com/naelstrof/UnityJigglePhysics.git#v7.0.2` rather than the upm branch?

same issue <img src="https://github.com/naelstrof/UnityJigglePhysics/assets/54823358/9139ad9d-40fa-4f9c-b361-7a19c08ed624" alt="HokoraCry" width="16">


https://github.com/naelstrof/UnityJigglePhysics/assets/54823358/6dd16d05-e2d5-4306-8a33-802ed22653e8

**Comment by HokoraYinphineMPP** [comment]
> I usually just put the git URL I need within the unity package manager.
I'm sorry im not sure any other way of importing through UPM... <img src="https://github.com/naelstrof/UnityJigglePhysics/assets/54823358/b92b50c0-be3b-478e-9978-d078d1e305c4" alt="HokoraSmileSweat" width="16"> Is that not how you normally do it?

**Comment by naelstrof** [comment]
You installed it correctly. I still have no idea why you're getting those errors. It's saying JiggleRigBuilder is missing. It's right there. It's in the same folder under the same namespace. My only thought is maybe they're getting compiled into separate dlls? Though the assembly definition is also just right there.

It doesn't help that it works fine on my system.

Can you verify that in your `Packages/Jiggle Physics/Scripts` that the two files belong to the same dll?

https://github.com/naelstrof/UnityJigglePhysics/assets/1131571/d8745684-78db-4658-8b99-e53cea84954d

**Comment by naelstrof** [comment]
OH. YOURE. YOU'RE NOT USING IT FOR GAME DEV

**Comment by naelstrof** [comment]
You don't need to install jiggle physics directly, you already have it installed with the model sdk!!!

**Comment by naelstrof** [comment]
The jiggle physics is embedded directly into the sdk, as that's how it gets pack-ratted into Lethal Company without introducing extra dependencies. The original jiggle physics is not compatible with the packratted version. Just uninstall it! (You'll still have jiggle rig builders available!)

**Comment by HokoraYinphineMPP** [comment]
OML it worked im crying 
tysm <3 <img src="https://github.com/naelstrof/UnityJigglePhysics/assets/54823358/7c4f1439-fd27-4aa0-a209-9a83d3b5caa4" alt="HokoraHappy" width="16">
