### ISSUE TITLE
Jiggle physics work fine in unity editor, but don't work at all in game.

### ISSUE THREAD

**Issue by Callff** [naelstrof/UnityJigglePhysics#28]
Creating a playermodel mod for Lethal Company - I added some jiggle physics to the model, and it works perfectly fine in the unity editor, but it just won't work in game. I've tried multiple different combinations of settings and such to no success. Is this a known issue? is there a fix for it? because I can't find one.

**Comment by naelstrof** [comment]
Don't install from git, use the one bundled with the Character Replacement SDK

**Comment by Callff** [comment]
I had actually installed from git (spent about 2 hours trying to figure out why the console was spitting out tons of errors) but have since removed the second (redundant) install before I was having this issue. Is there something else I need to do to fully remove it that I'm not aware of? clean caches or something like that? make a fresh project? I assumed I was successful in removing it because the console isn't giving any errors anymore.

**Comment by Callff** [comment]
Found the problem (or at least a fix). I deleted the Model Replacement Properties (Character Replacement SDK component) from my playermodel and then went through the process of setting up the playermodel again.
