### ISSUE TITLE
JiggleBoneSphereCollider is leaked

### ISSUE THREAD

**Issue by artnamed** [naelstrof/UnityJigglePhysics#29]
Hello
JigglePhysics is great, but I found an issue

Since the commit "Jiggle skin now reuses jiggle bone code for simulation." at tag v7.0.0, JiggleSkin generates a JiggleBoneSphereCollider and leaves it enabled in the Default layer

This collider collides with physics and creates holes in NavMeshComponents.
![2024-02-11 16_38_46-Unity 2022 3 14f1 _DX11_](https://github.com/naelstrof/UnityJigglePhysics/assets/11413397/9788f835-5cc4-40ee-9da8-579ae2466fc7)

I found similar Advance code in JiggleRigBuilder. CachedSphereCollider usages seems like has lost FinishedPass call in JiggleSkin
![2024-02-11 17_07_16-](https://github.com/naelstrof/UnityJigglePhysics/assets/11413397/4abe80b1-a501-4725-bf61-3904196fa218)
![2024-02-11 16_54_57-](https://github.com/naelstrof/UnityJigglePhysics/assets/11413397/fd43a4ff-5c44-480d-a652-85bf1d7fcbfa)

This leads to the collider remaining enabled in the scene

I'm not sure how it works, it would be nice if you could fix it properly

**Comment by naelstrof** [comment]
This should be fixed with v7.0.1 63040cd. Let me know if that fixes your issue!

**Comment by naelstrof** [comment]
Oh!! Whoops, no you're right jiggle skin is missing a call.

**Comment by naelstrof** [comment]
I pushed a fix that should also track jiggle skins properly. My bad I don't actually use jiggle skin that much in my projects so I never noticed! Try tag v7.0.3 for me and see if that fixes your issue!

**Comment by artnamed** [comment]
Thanks a lot!
