### ISSUE TITLE
unitypackage

### ISSUE THREAD

**Issue by newprogrammeram** [naelstrof/UnityJigglePhysics#33]
pleaqse upload unitypacke into fixed

**Comment by naelstrof** [comment]
There's instructions on how to install the program via the built-in package manager. Though you will need git installed.

You can install it via commandline with `winget install git` if you're on windows, and if you're on linux you can use your package manager.

If that doesn't work for you, you can download and move the folders yourself from [here](https://github.com/naelstrof/UnityJigglePhysics/tree/main/Assets/JigglePhysics).

Sorry, it'd be neat to also include a unity package, though I'd need to automate it somehow. Let me know if you have questions here so it can help other users with the same issue.
