### ISSUE TITLE
[Bug] Bones are not properly initialized when scene is not reloaded upon starting play mode

### ISSUE THREAD

**Issue by PereViader** [naelstrof/UnityJigglePhysics#35]
When Reload Scene is disabled
![image](https://github.com/user-attachments/assets/0fa8d172-3860-4939-b2bd-b6b8452c3efd)

Any changes in bone position are not properly picked up until play mode is started twice if the game was already played beforehand.

Unity 2022.3.29f1
UnityJigglePhysics 10.0.9

Steps to reproduce:

- Open unity
- Setup the enter play mode settings just like in the photo above
-  Create any rig with bones
- Add `JiggleRigBuilder` component and add a Jiggle rig to it. Jiggle Rig must have a chain of more than 1 children.
- Press Play
- Notice it works fine
- Press Play again to stop playing
- Move some of the children jiggle bones
- Press play
- Notice that the bones move back to the initial position <-- bug
- Press play to stop playing
- Press play
- Notice that now it works properly again

This might not happen if the scene is not entered directly from the editor. Probably related with leftover serialized data that is not cleaned up.

As a developer this hinders the ability to quickly iterate on the same scene I want to develop on.

**Comment by naelstrof** [comment]
My bad! I did test for disabling domain reload, but not disabling scene reload. It should be fixed now, please reopen if you have other troubles.
