### ISSUE TITLE
JiggleRig2dBuilder for sprite based rig implementations

### ISSUE THREAD

**Issue by PereViader** [naelstrof/UnityJigglePhysics#36]
When working with 2d sprites rigs where we want to implement jiggle functionality, JiggleRigBuilder can currently be used, but I believe it is not ideal for a 2D workflow.

Imagine the following case

![image](https://github.com/user-attachments/assets/2bc2309d-7928-4910-8b09-409961d5868b)

Where we have 3 transforms A, B, C in some positions on the XY plane. This is because we are in a 2D workflow

However, those 3 points actually represent something that might benefit from being aware about its actual 3rd Z dimension.

![image](https://github.com/user-attachments/assets/398b1f6e-f953-4853-af68-a35da691a8db)

Using JiggleRigBuilder, we can actually add the 3rd dimension to the transforms and the jiggle calculations look way nicer because the calculations are more accurate.

However, this also means that skinned sprites are actually deformed and that we must be really aware of the Z position of other sprites because the jiggle rig takes far more space on the Z axis that it initially did. It also means that we can't really rotate the camera.

Thus, having a JiggleRig2dBuilder that facilitates jiggle rigs that work on a single plane but are still able to have information about the third axis would be a great addition to this package.

Specific to my use case, for instance, I am currently having the Z translated length L = AB + BC   to be equal to some editor driven value. Then I can have more than one Jiggle Rig that have different relative positions ABC and DEF thus different initial length on the XY plane AB+BC = X and DE + EF = Y ,  to have length L after both have the the Z translation applied A'B' + B'C' = L  and D'E' + E'F' = L and thus, even if both look visually distinct on the XY plane, by having this translation they can both have the same Jiggle feel to them because part of the jiggle feel is accomplished with the length between the points.

![image](https://github.com/user-attachments/assets/653aad81-f43f-4bc2-a5d0-25bda4878f21)

Hope it makes sense :)
Let me know if I can clarify anything and/or if this request actually makes sense.

**Comment by naelstrof** [comment]
Thanks for the detailed explanation of your needs! While this would unquestionably make UnityJigglePhysics better, unfortunately UnityJigglePhysics is designed for 3D only, and we have no plans for 2D games. It is an unreasonable feature for us to try to maintain.

However what you're asking shouldn't be too difficult to integrate yourself. Ideally you'd simply edit the [PoseBone()](https://github.com/naelstrof/UnityJigglePhysics/blob/main/Assets/JigglePhysics/Scripts/JiggleBone.cs#L290) function, projecting the final position (right after SetPositionAndRotation, line 300) to the plane in question. (Though the length adjustments might need an additional pass, this should get you really close).

That would allow you to completely undisturb the simulation, while adjusting the looks to your taste. It also prevents us from having to maintain a feature we don't use. Hopefully keeping us all happy.

I hope that helps!

**Comment by Archival1** [comment]
@PereViader I know this might not be doable depending on the way you have this set up but have you tried using a copy of the bones that you have the jiggle enabled on and then constrain the real ones to the copies (with the jiggle script being on the copy only)?

That should allow you to control what plane you allow rotation by turning off the constrain on certain axis while still having the copy of the bones simulated in 3d space.

**Comment by PereViader** [comment]
@naelstrof I'd prefer to keep the implementation outside the package. I'd rather not have custom changes.

@Archival1 Did not really think about this option and I think it's great :)
Have an invisible 3d structure where to run the simulation on and then just have a post process that moves the actual visual 2d nodes using the invisible simulation.

In order to run that post process I am currently not looking at the code but I don't recall any event callback I could hook this to.
I guess either altering the execution order (don't really like it) or implementing a custom late update runner will be the way to execute it at the right time.
